### ISSUE TITLE
希望能把收益库存那块也搬过来

### ISSUE THREAD

**Issue by lvaneasylam** [taxilng/fundsForWeb#4]
找了这个挺久的，一直想要有一个可以直接自己弄在服务器上看的，然后看到那个插件之后，就在想要那个插件的网页版，可能这个已经挺好的，要是有收益那些可以看看就好了，希望能把收益那块也搬过来。加油！！！

**Comment by taxilng** [comment]
具体是指什么收益库存啊？可以提供下截图。
