### ISSUE TITLE
希望加上部署文档

### ISSUE THREAD

**Issue by liuzjMr** [taxilng/fundsForWeb#5]

**Comment by lvaneasylam** [comment]
下面readme不就是部署文档了吗

**Comment by liuzjMr** [comment]
vue build 之后，服务器的nginx如何配置代理，如何可以请分享一下演示地址服务器的nginx配置

**Comment by lvaneasylam** [comment]
有一个dist的文件夹，nginx指向那个文件夹下，自动会读取那个index.html的

**Comment by liuzjMr** [comment]
请问nginx接口代理如何配置，例如fundMApi和fundsuggest这些接口

发自我的iPhone

**Comment by lvaneasylam** [comment]
我不知道这些接口，我只是打开页面看看而已

**Comment by liuzjMr** [comment]
这些接口不配置nginx代理是请求不通的😂😂😂

发自我的iPhone

**Comment by taxilng** [comment]
有部署的配置文件的，根目录nginx.conf
